#!/bin/bash

centerskin=false
erosion=false
dilation=false

w=1920
h=1080

param=''
[ $centerskin == true ] && param="$param --allow-center-skin"
[ $erosion == true ] && param="$param --with-erosion"
[ $erosion == false ] && param="$param --without-erosion"
[ $dilation == true ] && param="$param --with-dilation"
[ $dilation == false ] && param="$param --without-dilation"
[ "$w" ] && param="$param -w $w"
[ "$h" ] && param="$param -h $h"

run() {
	echo bin/cvgame $param "$@"
	bin/cvgame $param "$@"
}

if [ -z "$1" ]; then
	make clean
	make -j8
fi

clear
echo tracking demo
read
run --tracking-demo
clear
echo 1 ball
read
run
clear
echo 5 balls
read
run --max-ball-count 5
clear
echo appear / disappearing balls
read
run --max-ball-count 5 --spawn-remove-balls
clear
echo koike ball
read
run --max-ball-count 5 --spawn-remove-balls --enable-koike
clear
echo spin
read
run --max-ball-count 5 --spawn-remove-balls --enable-koike --enable-spin
clear
echo gore
read
run --max-ball-count 5 --spawn-remove-balls --enable-koike --enable-spin --enable-gore
clear
echo game
read
run --game

