#!/bin/bash

centerskin=false
erosion=false
dilation=false

w=1920
h=1080

param=''
[ $centerskin == true ] && param="$param --allow-center-skin"
[ $erosion == true ] && param="$param --with-erosion"
[ $erosion == false ] && param="$param --without-erosion"
[ $dilation == true ] && param="$param --with-dilation"
[ $dilation == false ] && param="$param --without-dilation"
[ "$w" ] && param="$param -w $w"
[ "$h" ] && param="$param -h $h"

run() {
	echo bin/cvgame $param "$@"
	bin/cvgame $param "$@"
}

if [ -z "$1" ]; then
	make clean
	make -j8
fi


module=uvcvideo
lsmod | grep "$module" &>/dev/null || sudo modprobe $(module)


clear
echo tracking demo
echo
echo toggle tracking with T!
read
run --tracking-demo
clear
echo 1 ball
read
run
clear
echo 5 balls
echo
echo next: disappearing balls
read
run --max-ball-count 5
clear
echo appear / disappearing balls
echo
echo disappearing balls are boring...
read
run --max-ball-count 5 --spawn-remove-balls
clear
#echo koike ball
echo textured ball with spin
echo
#echo next: spin
#read
#run --max-ball-count 5 --spawn-remove-balls --enable-koike
#clear
#echo spin
#echo
#echo enable mp with M!
read
run --max-ball-count 5 --spawn-remove-balls --enable-koike --enable-spin
clear
echo gore / balls filled with water
read
run --max-ball-count 5 --spawn-remove-balls --enable-koike --enable-spin --enable-gore --enable-mp
clear
echo game
echo
echo toggle safe mode with S
read
run --game --enable-mp

